<?php

namespace ContainerG3ZItm3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HelWCOW.App\Entity\Professeur' shared service.
     *
     * @return \App\Entity\Professeur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HelWCOW": it references class "App\\Entity\\Professeur" but no such service exists.');
    }
}
