<?php

namespace ContainerTIHmtwI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__3XAv19Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..3XAv19' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..3XAv19'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'professeur' => ['privates', '.errored..service_locator..3XAv19.App\\Entity\\Professeur', NULL, 'Cannot autowire service ".service_locator..3XAv19": it references class "App\\Entity\\Professeur" but no such service exists.'],
        ], [
            'em' => '?',
            'professeur' => 'App\\Entity\\Professeur',
        ]);
    }
}
