<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZwQ5CeE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZwQ5CeE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZwQ5CeE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZwQ5CeE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZwQ5CeE\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZwQ5CeE',
    'container.build_id' => 'f5cd757a',
    'container.build_time' => 1646743354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZwQ5CeE');
