<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG3ZItm3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3ZItm3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG3ZItm3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG3ZItm3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG3ZItm3\App_KernelDevDebugContainer([
    'container.build_hash' => 'G3ZItm3',
    'container.build_id' => '0a0e373f',
    'container.build_time' => 1646298895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3ZItm3');
