<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'api_professeurslist' => [[], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::list'], [], [['text', '/api/professeurs']], [], [], []],
    'api_professeursshow' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], [], []],
    'api_professeursavis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::avis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], [], []],
    'api_professeurscreate_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::createAvis'], [], [['text', '/avis'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs']], [], [], []],
    'api_professeursdelete_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::deleteAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs/avis']], [], [], []],
    'api_professeursedit_avis' => [['id'], ['_controller' => 'App\\Controller\\Api\\ProfesseurController::editAvis'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/professeurs/avis']], [], [], []],
    'professeurs_list' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::list'], [], [['text', '/professeurs/']], [], [], []],
    'professeurs_create' => [[], ['_controller' => 'App\\Controller\\ProfesseurController::create'], [], [['text', '/professeurs/create']], [], [], []],
    'professeurs_edit' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs']], [], [], []],
    'professeurs_delete' => [['id'], ['_controller' => 'App\\Controller\\ProfesseurController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/professeurs']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
